### ISSUE TITLE
RequestResponse(status_code=404, text='{"errors":[{"message":"Sorry, that page does not exist","code":34}]}')

### ISSUE THREAD

**Issue by yamin8000** [markowanga/stweet#103]
```python
import stweet as st


def try_search():
    search_tweets_task = st.SearchTweetsTask(all_words='#covid19')
    output_jl_tweets = st.JsonLineFileRawOutput('output_raw_search_tweets.jl')
    output_jl_users = st.JsonLineFileRawOutput('output_raw_search_users.jl')
    output_print = st.PrintRawOutput()
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                         tweet_raw_data_outputs=[output_print, output_jl_tweets],
                         user_raw_data_outputs=[output_print, output_jl_users]).run()


try_search()
```
stacktrace

```
Traceback (most recent call last):
  File "...\python_test_site\main.py", line 14, in <module>
    try_search()
  File "...\python_test_site\main.py", line 11, in try_search
    user_raw_data_outputs=[output_print, output_jl_users]).run()
  File "...\Python\Python310\lib\site-packages\stweet\search_runner\search_runner.py", line 51, in run
    self._execute_next_tweets_request()
  File "...\Python\Python310\lib\site-packages\stweet\search_runner\search_runner.py", line 71, in _execute_next_tweets_request
    raise ScrapBatchBadResponse(response)
stweet.exceptions.scrap_batch_bad_response.ScrapBatchBadResponse: RequestResponse(status_code=404, text='{"errors":[{"message":"Sorry, that page does not exist","code":34}]}')
```

**Comment by alizia** [comment]
Bump

**Comment by BelugaWhale** [comment]
Bump

**Comment by FrancescoVassalli** [comment]
@markowanga Hi and thanks for making this. Are you still maintaining this repo? Is it just impossible to support this with constant changes from Twitter? Could this issue be a tor vs no tor issue? I am trying to decide how much effort to put into implementing this

**Comment by innocentius** [comment]
Sorry for reopening the issue, but the problem still exists and people are still asking this question.

Is the repo still being maintained?
