### ISSUE TITLE
RequestResponse(status_code=403, text='{"errors":[{"code":200,"message":"Forbidden."}]}')

### ISSUE THREAD

**Issue by Kedao98** [markowanga/stweet#106]
```python3
import arrow
import stweet as st


def try_search():
    search_tweets_task = st.SearchTweetsTask(all_words='#covid19', since=dt, until=dt2)
    output_jl_tweets = st.JsonLineFileRawOutput('output_raw_search_tweets.jl')
    output_jl_users = st.JsonLineFileRawOutput('output_raw_search_users.jl')
    output_print = st.PrintRawOutput()
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                         tweet_raw_data_outputs=[output_print, output_jl_tweets],
                         user_raw_data_outputs=[output_print, output_jl_users]).run()


dt = arrow.Arrow(2023, 4, 20, 9, 30, 0)
dt2 = arrow.Arrow(2023, 4, 20, 9, 31, 0)
try_search() 
```
traceback
```
Traceback (most recent call last):
  File "/Users/kedao/Desktop/OPAY/ng-twitter-spider/new_twitter_spider.py", line 31, in <module>
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
  File "/Users/kedao/miniforge3/envs/anaconda_base/lib/python3.8/site-packages/stweet/search_runner/search_runner.py", line 51, in run
    self._execute_next_tweets_request()
  File "/Users/kedao/miniforge3/envs/anaconda_base/lib/python3.8/site-packages/stweet/search_runner/search_runner.py", line 71, in _execute_next_tweets_request
    raise ScrapBatchBadResponse(response)
stweet.exceptions.scrap_batch_bad_response.ScrapBatchBadResponse: RequestResponse(status_code=403, text='{"errors":[{"code":200,"message":"Forbidden."}]}')
```

**Comment by jcgq** [comment]
Same problem here

**Comment by xymou** [comment]
Same problem. It seems that Twitter has changed the search page which now requires login first...

**Comment by Kedao98** [comment]
> Same problem. It seems that Twitter has changed the search page which now requires login first...

It might be caused by AIGC boom. A bound of companies want to train their model with twitter's data. Do you have a replacement of it?

**Comment by xymou** [comment]
> > Same problem. It seems that Twitter has changed the search page which now requires login first...
> 
> It might be caused by AIGC boom. A bound of companies want to train their model with twitter's data. Do you have a replacement of it?

No, I haven't solved this problem yet either.😢 I guess we need to get some twitter accounts to simulate login or get cookies.

**Comment by BradKML** [comment]
Sad and unfortunate. Would need to keep an ugly eye on open-access.

**Comment by BoeingConstrictor** [comment]
Any update to this? I am having the same problem.

**Comment by 1962983024** [comment]
(RequestResponse(status_code=403, text='{"errors":[{"code":200,"message":"Forbidden."}]}'),)
same problem

**Comment by dingteddy** [comment]
same problem

**Comment by justin-pierce** [comment]
is there no way to get a user's tweets without using the search? can't just scrape a profile and get the tweets?

**Comment by muskit** [comment]
Is there a way to pass an auth token? I can't find it in the source so far...

**Comment by zernel** [comment]
> stweet.exceptions.scrap_batch_bad_response.ScrapBatchBadResponse: RequestResponse(status_code=403, text='{"errors":[{"code":200,"message":"Forbidden."}]}')

Same problem....
