### ISSUE TITLE
Installing using setup.py on Windows fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by chillerno1** [markowanga/stweet#58]
I encountered a minor issue after cloning the repo and attempting to install the package through `python -m setup.py install`.

```powershell
(venv) C:\Users\Profile\PycharmProjects\stweet>python -m setup.py install
Traceback (most recent call last):
  File "C:\Users\Profile\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Profile\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Profile\PycharmProjects\stweet\setup.py", line 4, in <module>
    LONG_DESCRIPTION = fh.read()
  File "C:\Users\Profile\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2176: character maps to <undefined>
```

Will submit a PR shortly with this issue # with an update `setup.py` so that `encoding='utf-8'` is explicitly defined in the read blocks.

**Comment by markowanga** [comment]
Hi, I will check it Today, thank you for your PR, I have macOS and Linux installed :D

**Comment by markowanga** [comment]
Now project is on poetry :D
