### ISSUE TITLE
Scraper getting 404 Errors

### ISSUE THREAD

**Issue by alizia** [markowanga/stweet#98]
Hi, 

I've suddenly started getting the following error while running the scraper:

`RequestResponse(status_code=404, text='{"errors":[{"message":"Sorry, that page does not exist","code":34}]}'), retrying in 15 seconds...
`
I am using stweet version 2.1.0

Here's what my code looks like:

```
    tweets_collector = st.CollectorRawOutput()
    users_collector = st.CollectorRawOutput()

    search_tweets_task = st.SearchTweetsTask(
        all_words=search_term,
        since=since_date,
        until=until_date
    )
    web_client = st.RequestsWebClient(
        proxy=st.RequestsWebClientProxyConfig(
            http_proxy=socks5://localhost:9050,
            https_proxy=socks5://localhost:9050
        ),
        interceptors=[TwitterAuthWebClientInterceptor()]
    )
    st.TweetSearchRunner(
        search_tweets_task=search_tweets_task,
        tweet_raw_data_outputs=[tweets_collector],
        user_raw_data_outputs=[users_collector],
        web_client=web_client
    ).run()
```

I am unable to figure out why my requests are failing. Can you please help? Thanks!

**Comment by dqfrance** [comment]
I had the same problem from yesterday.

**Comment by markowanga** [comment]
Could you provide full code of example (not only a part)?

**Comment by alizia** [comment]
Sure! Here's a full example that demonstrates the problem:

```python
import arrow
import argparse
import stweet as st

from stweet.twitter_api.twitter_auth_web_client_interceptor import TwitterAuthWebClientInterceptor


PROXY_URL = 'socks5://localhost:9050'


def collect_tweets(search_term, tweets_collectors, users_collectors, since_date, until_date=None):
    """
    Run tweet collection and put results into provided collectors.
    :param search_term: Term for which to find tweets.
    :param tweets_collectors: A list of collectors with parent type RawDataOutput for the storage of tweets.
    :param users_collectors: A list of collectors with parent type RawDataOutput for the storage of user information
                             of users who wrote the tweets provided in the other collector.
    :param since_date: Arrow time object representing date starting which tweets should be searched.
    :param until_date: Arrow time object representing date up till which tweets should be searched.
    """
    search_tweets_task = st.SearchTweetsTask(
        all_words=search_term,
        since=since_date,
        until=until_date
    )
    web_client = st.RequestsWebClient(
        proxy=st.RequestsWebClientProxyConfig(
            http_proxy=PROXY_URL,
            https_proxy=PROXY_URL
        ),
        interceptors=[TwitterAuthWebClientInterceptor()]
    )
    st.TweetSearchRunner(
        search_tweets_task=search_tweets_task,
        tweet_raw_data_outputs=tweets_collectors,
        user_raw_data_outputs=users_collectors,
        web_client=web_client
    ).run()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--term', type=str)
    parser.add_argument('--since', type=str)
    parser.add_argument('--until', type=str)
    args = parser.parse_args()

    arrow_since = arrow.get(args.since, "YYYY-MM-DD") if args.since else None
    arrow_until = arrow.get(args.until, "YYYY-MM-DD") if args.until else None

    collect_tweets(
        args.term,
        st.PrintRawOutput(),
        st.PrintRawOutput(),
        arrow_since,
        arrow_until
    )
```

Run with the following command:
`python twitter_scraper.py --term musk --since 2023-01-10`

Returns the error stack:
```
Traceback (most recent call last):
  File "/Users/ali/Documents/code/twitter/twitter_scraper.py", line 51, in <module>
    collect_tweets(
  File "/Users/ali/Documents/code/twitter/twitter_scraper.py", line 33, in collect_tweets
    st.TweetSearchRunner(
  File "/Users/ali/Documents/code/venv/lib/python3.8/site-packages/stweet/search_runner/search_runner.py", line 50, in run
    self._execute_next_tweets_request()
  File "/Users/ali/Documents/code/venv/lib/python3.8/site-packages/stweet/search_runner/search_runner.py", line 70, in _execute_next_tweets_request
    raise ScrapBatchBadResponse(response)
stweet.exceptions.scrap_batch_bad_response.ScrapBatchBadResponse: RequestResponse(status_code=404, text='{"errors":[{"message":"Sorry, that page does not exist","code":34}]}')
```

**Comment by markowanga** [comment]
Thank you @alizia for the complete example.
It looks that twitter has changed something in API – I will check this in a few days. Example from readme does not work too.

**Comment by alizia** [comment]
Thank you @markowanga

**Comment by xianrenzhou** [comment]
I had the same problem from today.

**Comment by alizia** [comment]
@markowanga did you get a chance to take a look?

Just wanted to say - I really appreciate you creating and maintaining this project. It has been such a help and I can't wait to use it more and perhaps to contribute one day as well.

Again, thank you!

**Comment by Ahacad** [comment]
This seems to be related with TLS fingerprinting, many libraries also faced this problem about 2 weeks ago, maybe you could look into these issues: https://github.com/medialab/minet/issues/525, https://github.com/JustAnotherArchivist/snscrape/issues/647, https://github.com/mikf/gallery-dl/issues/3522, and these commits for fixing: https://github.com/medialab/minet/commit/4d80b1dd63537abb3078b8fd7ce8102887206853, https://github.com/JustAnotherArchivist/snscrape/commit/7de8d734e97acc2bc89c93d934b467d5596c6ca8

**Comment by markowanga** [comment]
Thank you :) I will check this

**Comment by markowanga** [comment]
I have released version 2.1.1 now it work correct

**Comment by alizia** [comment]
@markowanga Thank you so much for fixing.

@Ahacad Thank you very much for finding the solution!

**Comment by dqfrance** [comment]
Thank you so much for fixing!

**Comment by wenrenyueke** [comment]
>no, 2.1.1  it can't work 



> 我已经发布了 2.1.1 版，现在它可以正常工作

**Comment by SriyanAnuruddha** [comment]
i'm also getting this error. is their any solutions for that ?
